# Generated by Django 5.1.7 on 2025-03-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_profile',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='has_company_logo',
            field=models.BooleanField(default=False),
        ),
    ]
