# Generated by Django 5.1.7 on 2025-03-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_jobposting_company_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='company_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='domain_age_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='linkedin_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='social_media_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='ssl_valid',
            field=models.BooleanField(default=False),
        ),
    ]
