# Generated by Django 5.1.7 on 2025-03-09 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_jobposting_company_domain_jobposting_domain_age_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='company',
            new_name='company_name',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='domain_age_days',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='linkedin_exists',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='social_media_count',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='ssl_valid',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='explanation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='company_domain',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['company_domain'], name='api_jobpost_company_91490c_idx'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['created_at'], name='api_jobpost_created_7d2003_idx'),
        ),
    ]
