# Generated by Django 5.1.7 on 2025-03-27 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_company_jobposting_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='domain_age_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='linkedin_exists',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='social_media_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='ssl_valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['is_fake'], name='api_jobpost_is_fake_89920f_idx'),
        ),
    ]
